logging:
  level:
    root: info
    io.lzz: debug
    
spring:
  datasource:
    url: jdbc:h2:./tmp/test.db;AUTO_SERVER=TRUE
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
#    generate-ddl: true
    show-sql: true
    
 